name: Correction
description: Suggest a correction to the list!
title: "[Correction]"
labels: ["Correction"]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Issue will be closed if incomplete.
      options:
        - label: I've checked that this correction is valid and accurate.
          required: true
        - label: I've checked that this correction has not already been suggested.
          required: true
  - type: input
    attributes:
      label: What mod is this correction for?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What section(s) of the list is this correction for?
      multiple: true
      options:
        - Preformance
        - Bugfixes
        - Enhancements
        - Software
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What version(s) dose this correction apply to?
      multiple: true
      options:
        - 1.8.X or earlier
        - 1.12.X
        - 1.15.X (Forge)
        - 1.15.X (Fabric)
        - 1.16.X (Forge)
        - 1.16.X (Fabric)
        - 1.17.X (Forge)
        - 1.17.X (Fabric)
        - 1.18.X (Forge)
        - 1.18.X (Fabric)
        - Other (Forge)
        - Other (Fabric)
        - All versions
        - Not applicable
    validations:
      required: true
  - type: textarea
    attributes:
      label: What needs correcting?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Input a link(s) which can be used to verify the correction.
    validations:
      required: true
  - type: textarea
    attributes:
      label: (OPTIONAL) Any extra information about the correction.
