name: Correction
description: Suggest a correction to the list!
title: "[Correction]"
labels: ["Correction"]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Issue will be closed if incomplete. These are required before submitting and by sumbitting you agree that you have actually done them.
      options:
        - label: I've checked that this correction is valid and accurate.
          required: true
        - label: I've checked that this correction has not already been suggested.
          required: true
  - type: input
    attributes:
      label: What mod is this correction for?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What section(s) of the list is this correction for?
      description: Select all that apply. Where the mod is located in the lists
      multiple: true
      options:
        - Performance
        - Bugfixes
        - Enhancements
        - Software
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What version(s) does this correction apply to?
      multiple: true
      options:
        - 1.8.X or earlier
        - 1.12.X
        - 1.15.X (Forge)
        - 1.15.X (Fabric)
        - 1.16.X (Forge)
        - 1.16.X (Fabric)
        - 1.17.X (Forge)
        - 1.17.X (Fabric)
        - 1.18.X (Forge)
        - 1.18.X (Fabric)
        - 1.19.X (Forge)
        - 1.19.X (Fabric)
        - 1.20.X (Forge)
        - 1.20.X (Fabric)
        - Other (Forge)
        - Other (Fabric)
        - All versions
        - Not applicable
    validations:
      required: true
  - type: textarea
    attributes:
      label: What needs correcting?
      description: Please provide a detailed description of the correction. If you are correcting a link, please provide the correct link.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Input relevant link(s) which can be used to verify the correction.
      description: Please provide a link to the source of the correction. Pictures are also accepted if they are relevant. Such as a screenshot of response from the mod author.
    validations:
      required: true
  - type: textarea
    attributes:
      label: (OPTIONAL) Any extra information about the correction.
